[toggl]
api_token = "<get the token from toggl>"
workspace = "the workspace you want tracked"

[google_api]
spreadsheet_id = "<insert the long ass sheet id>"
credentials_file = "creds/credentials.json"
token_file = "creds/token.pickle"
project_sheet="Projects!A5:B"
time_sheet="timesheet!A2:D"
date_format ="%Y-%m-%d"

[local]
## If you want to persist your sqlitedb:
# sqlite_db = "timewriggler.db"

## If you want to store things in memory:
sqlite_db = "file::memory:?cache=shared"