SCHEMA = dict(
    project=[
        "id INT PRIMARY KEY NOT NULL",
        "wid INT NOT NULL",
        "cid INT",
        "name TEXT",
        "billable BOOL",
        "is_private BOOL",
        "active BOOL",
        "template BOOL",
        "at DATETIME",
        "created_at DATETIME",
        "color TEXT",
        "auto_estimates BOOL",
        "actual_hours INT",
        "hex_color TEXT",
    ],
    workspace=[
        "id INT PRIMARY KEY NOT NULL",
        "name TEXT",
        "profile INT",
        "premium BOOL",
        "admin BOOL",
        "default_hourly_rate INT",
        "default_currency TEXT",
        "only_admins_may_create_projects BOOL",
        "only_admins_see_billable_rates BOOL",
        "only_admins_see_team_dashboard BOOL",
        "projects_billable_by_default BOOL",
        "rounding INT",
        "rounding_minutes INT",
        "api_token TEXT",
        "at DATETIME",
        "ical_enabled BOOL",
    ],
    time_entries=[
        "id INT PRIMARY KEY NOT NULL",
        "guid TEXT",
        "wid INT",
        "pid INT",
        "billable BOOL",
        "start DATETIME NOT NULL",
        "stop DATETIME",
        "duration INT",
        "description TEXT",
        "duronly BOOL",
        "at DATETIME",
        "uid INT",
    ],
    project_name=["id INT PRIMARY KEY NOT NULL", "name TEXT"],
)
